Add explicit dependency to epel-rpm-macros on rhel
The meson package provides also rpm build macro %meson.
This macro is using %set_build_flags, which is missing on RHEL.
Macro is on RHEL provided  by the epel-rpm-macros package

Sample error log:
$ rpmbuild -ba radare2.spec 
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.9HbYwq
+ umask 022
+ cd /buildroot/rpmbuild/BUILD
+ cd /buildroot/rpmbuild/BUILD
+ rm -rf radare2-5.2.0
+ /usr/bin/gzip -dc /buildroot/rpmbuild/SOURCES/radare2-5.2.0.tar.gz
+ /usr/bin/tar -xf -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd radare2-5.2.0
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ rm -rf shlr/zip shlr/lz4
+ rm -rf ./shlr/www/console.html ./shlr/www/d3 ./shlr/www/f ./shlr/www/favicon.ico ./shlr/www/graph ./shlr/www/index.html ./shlr/www/index.old.html ./shlr/www/log.html ./shlr/www/m ./shlr/www/old ./shlr/www/r2.svg ./shlr/www/rlogo.png ./shlr/www/t ./shlr/www/upload.html
+ echo 'The radare2 source usually comes with a pre-built version of the web-interface, but without the source code.'
+ echo 'This has been removed in the Fedora package to follow the Fedora Packaging Guidelines.'
+ echo 'Available under https://github.com/radare/radare2-webui'
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.03pSq9
+ umask 022
+ cd /buildroot/rpmbuild/BUILD
+ cd radare2-5.2.0
+ %set_build_flags
/var/tmp/rpm-tmp.03pSq9: line 31: fg: no job control
error: Bad exit status from /var/tmp/rpm-tmp.03pSq9 (%build)